version: "3.1"

services:
  db:
    image: mongo
    profiles:
      - dev
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: my_db

  api:
    profiles:
      - dev
    build:
      context: .
      target: base
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASSWORD: example
      DB_URL: mongodb://root:example@db:27017
volumes:
  code:
